language: python
cache: pip
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
  - pypy3
jobs:
  include:
    - name: flake8
      python: 3.8
      install: pip install tox
      script: tox -e flake8
      after_success:
    - name: isort
      python: 3.8
      install: pip install tox
      script:
        - tox -e isort
      after_success:
    # coveralls.io never reports commit statuses for some reason, and of course
    # you don't get support for a free product
    - name: coverage
      python: 3.8
      install: pip install tox
      script:
        - tox -e coverage
      after_success:
install:
  - pip install coverage coveralls -cconstraints.txt
  - pip install freezegun flake8
  - pip install --no-deps -e .
script:
  - coverage run -m gtimelog.tests
after_success:
  - coveralls

notifications:
  irc:
    channels:
      - "chat.freenode.net##mgedmin"
    on_success: change
    on_failure: always
    template:
      # ping my nick so I get a pushbullet notification on my phone
      - "mgedmin: %{repository_name} (%{branch}) build %{result}: %{build_url}"
